# Generated by Django 3.1.5 on 2021-02-24 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210218_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='guest_user',
            field=models.BooleanField(default=False, verbose_name='ゲスト'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='current_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.student', verbose_name='利用者'),
        ),
        migrations.AlterField(
            model_name='student',
            name='hr_grade',
            field=models.CharField(choices=[('M1', 'M1'), ('M2', 'M2'), ('M3', 'M3'), ('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3')], max_length=5, verbose_name='学年'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.IntegerField(verbose_name='座席番号')),
                ('guest_user', models.BooleanField(default=False, verbose_name='ゲスト')),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.student', verbose_name='利用者')),
            ],
        ),
    ]
